Enhancement/ConfirmSelectionButton
PerigonGames/Party-Parkade pull request #446
Opened 2020-09-30 06:24 UTC by m4rtint

<img width="942" alt="Screen Shot 2020-09-30 at 2 20 20 AM" src="https://user-images.githubusercontent.com/5779541/94650109-0ecb9280-02c4-11eb-8f9a-0f93fb49583a.png">

2020-09-30 06:25 UTC, m4rtint commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add spritesheet of confirm keys into Player Selection (0.5)](https://trello.com/c/9a0WRg2V/903-add-spritesheet-of-confirm-keys-into-player-selection-05)

2020-09-30 19:13 UTC, Gursaanj reviewed
Oh makes sense!!

2020-09-30 19:13 UTC, Gursaanj commented on Assets/_PartyParkade/Script/UI/MainMenu/PlayerSelection/PlayerSelectionVC/ConfirmViewController.cs
> +﻿using InControl;
Missing Header

2020-09-30 20:11 UTC, m4rtint commented on Assets/_PartyParkade/Script/UI/MainMenu/PlayerSelection/PlayerSelectionVC/ConfirmViewController.cs
> +﻿using InControl;
Updated

2020-09-30 21:20 UTC, Gursaanj approved these changes

2020-10-01 21:06 UTC, Gursaanj requested changes
![image](https://user-images.githubusercontent.com/23490604/94863385-39663a00-03ef-11eb-8d95-182fdbe7a953.png)
Need to unsubscribe from these methods

2020-10-01 21:33 UTC, m4rtint commented
> ![image](https://user-images.githubusercontent.com/23490604/94863385-39663a00-03ef-11eb-8d95-182fdbe7a953.png)
> Need to unsubscribe from these methods

replied on slack.
I null the viewModel, it's fine

2020-10-01 21:36 UTC, Gursaanj approved these changes

2020-10-01 21:43 UTC, wbeltran777 approved these changes
Looks all good

2020-10-01 21:43 UTC, merged